project:
  type: website

website:
  title: "Anna's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About  
      - href: Projects.qmd
        text: Projects  
      - href: Courses.qmd
        text: Courses

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



